CREATE TABLE IF NOT EXISTS puzzles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    img VARCHAR(255) NOT NULL,
    best_time BIGINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_played TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_best_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);